// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: mappings.sql

package models

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addServiceToSection = `-- name: AddServiceToSection :one
INSERT INTO service_section_mappings (service_id, section_id, sort_order)
VALUES ($1, $2, $3)
ON CONFLICT (service_id, section_id) DO NOTHING
RETURNING id, service_id, section_id, sort_order, created_at
`

type AddServiceToSectionParams struct {
	ServiceID pgtype.UUID `json:"service_id"`
	SectionID pgtype.UUID `json:"section_id"`
	SortOrder int32       `json:"sort_order"`
}

func (q *Queries) AddServiceToSection(ctx context.Context, arg AddServiceToSectionParams) (ServiceSectionMapping, error) {
	row := q.db.QueryRow(ctx, addServiceToSection, arg.ServiceID, arg.SectionID, arg.SortOrder)
	var i ServiceSectionMapping
	err := row.Scan(
		&i.ID,
		&i.ServiceID,
		&i.SectionID,
		&i.SortOrder,
		&i.CreatedAt,
	)
	return i, err
}

const deleteMappingsByService = `-- name: DeleteMappingsByService :exec
DELETE FROM service_section_mappings WHERE service_id = $1
`

func (q *Queries) DeleteMappingsByService(ctx context.Context, serviceID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteMappingsByService, serviceID)
	return err
}

const listMappingsBySection = `-- name: ListMappingsBySection :many
SELECT id, service_id, section_id, sort_order, created_at FROM service_section_mappings
WHERE section_id = $1
ORDER BY sort_order ASC
`

func (q *Queries) ListMappingsBySection(ctx context.Context, sectionID pgtype.UUID) ([]ServiceSectionMapping, error) {
	rows, err := q.db.Query(ctx, listMappingsBySection, sectionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ServiceSectionMapping{}
	for rows.Next() {
		var i ServiceSectionMapping
		if err := rows.Scan(
			&i.ID,
			&i.ServiceID,
			&i.SectionID,
			&i.SortOrder,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSectionIDsByService = `-- name: ListSectionIDsByService :many
SELECT section_id FROM service_section_mappings WHERE service_id = $1
`

func (q *Queries) ListSectionIDsByService(ctx context.Context, serviceID pgtype.UUID) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, listSectionIDsByService, serviceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var section_id pgtype.UUID
		if err := rows.Scan(&section_id); err != nil {
			return nil, err
		}
		items = append(items, section_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeServiceFromSection = `-- name: RemoveServiceFromSection :exec
DELETE FROM service_section_mappings
WHERE service_id = $1 AND section_id = $2
`

type RemoveServiceFromSectionParams struct {
	ServiceID pgtype.UUID `json:"service_id"`
	SectionID pgtype.UUID `json:"section_id"`
}

func (q *Queries) RemoveServiceFromSection(ctx context.Context, arg RemoveServiceFromSectionParams) error {
	_, err := q.db.Exec(ctx, removeServiceFromSection, arg.ServiceID, arg.SectionID)
	return err
}

const updateMappingSortOrder = `-- name: UpdateMappingSortOrder :exec
UPDATE service_section_mappings
SET sort_order = $3
WHERE service_id = $1 AND section_id = $2
`

type UpdateMappingSortOrderParams struct {
	ServiceID pgtype.UUID `json:"service_id"`
	SectionID pgtype.UUID `json:"section_id"`
	SortOrder int32       `json:"sort_order"`
}

func (q *Queries) UpdateMappingSortOrder(ctx context.Context, arg UpdateMappingSortOrderParams) error {
	_, err := q.db.Exec(ctx, updateMappingSortOrder, arg.ServiceID, arg.SectionID, arg.SortOrder)
	return err
}
