// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package models

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Section struct {
	ID          pgtype.UUID        `json:"id"`
	Name        string             `json:"name"`
	Icon        string             `json:"icon"`
	Cols        int32              `json:"cols"`
	Collapsed   bool               `json:"collapsed"`
	SortOrder   int32              `json:"sort_order"`
	SectionType string             `json:"section_type"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type Service struct {
	ID             pgtype.UUID        `json:"id"`
	Title          string             `json:"title"`
	Url            string             `json:"url"`
	Description    string             `json:"description"`
	Icon           string             `json:"icon"`
	StatusCheck    bool               `json:"status_check"`
	StatusCheckUrl pgtype.Text        `json:"status_check_url"`
	SortOrder      int32              `json:"sort_order"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type ServiceSectionMapping struct {
	ID        pgtype.UUID        `json:"id"`
	ServiceID pgtype.UUID        `json:"service_id"`
	SectionID pgtype.UUID        `json:"section_id"`
	SortOrder int32              `json:"sort_order"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}
