// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sections.sql

package models

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSection = `-- name: CreateSection :one
INSERT INTO sections (name, icon, cols, collapsed, sort_order, section_type)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, name, icon, cols, collapsed, sort_order, section_type, created_at, updated_at
`

type CreateSectionParams struct {
	Name        string `json:"name"`
	Icon        string `json:"icon"`
	Cols        int32  `json:"cols"`
	Collapsed   bool   `json:"collapsed"`
	SortOrder   int32  `json:"sort_order"`
	SectionType string `json:"section_type"`
}

func (q *Queries) CreateSection(ctx context.Context, arg CreateSectionParams) (Section, error) {
	row := q.db.QueryRow(ctx, createSection,
		arg.Name,
		arg.Icon,
		arg.Cols,
		arg.Collapsed,
		arg.SortOrder,
		arg.SectionType,
	)
	var i Section
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Icon,
		&i.Cols,
		&i.Collapsed,
		&i.SortOrder,
		&i.SectionType,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSection = `-- name: DeleteSection :exec
DELETE FROM sections WHERE id = $1
`

func (q *Queries) DeleteSection(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteSection, id)
	return err
}

const getSection = `-- name: GetSection :one
SELECT id, name, icon, cols, collapsed, sort_order, section_type, created_at, updated_at FROM sections WHERE id = $1
`

func (q *Queries) GetSection(ctx context.Context, id pgtype.UUID) (Section, error) {
	row := q.db.QueryRow(ctx, getSection, id)
	var i Section
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Icon,
		&i.Cols,
		&i.Collapsed,
		&i.SortOrder,
		&i.SectionType,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSections = `-- name: ListSections :many
SELECT id, name, icon, cols, collapsed, sort_order, section_type, created_at, updated_at FROM sections ORDER BY sort_order ASC
`

func (q *Queries) ListSections(ctx context.Context) ([]Section, error) {
	rows, err := q.db.Query(ctx, listSections)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Section{}
	for rows.Next() {
		var i Section
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Icon,
			&i.Cols,
			&i.Collapsed,
			&i.SortOrder,
			&i.SectionType,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSection = `-- name: UpdateSection :one
UPDATE sections
SET name = $2, icon = $3, cols = $4, collapsed = $5, sort_order = $6, section_type = $7, updated_at = now()
WHERE id = $1
RETURNING id, name, icon, cols, collapsed, sort_order, section_type, created_at, updated_at
`

type UpdateSectionParams struct {
	ID          pgtype.UUID `json:"id"`
	Name        string      `json:"name"`
	Icon        string      `json:"icon"`
	Cols        int32       `json:"cols"`
	Collapsed   bool        `json:"collapsed"`
	SortOrder   int32       `json:"sort_order"`
	SectionType string      `json:"section_type"`
}

func (q *Queries) UpdateSection(ctx context.Context, arg UpdateSectionParams) (Section, error) {
	row := q.db.QueryRow(ctx, updateSection,
		arg.ID,
		arg.Name,
		arg.Icon,
		arg.Cols,
		arg.Collapsed,
		arg.SortOrder,
		arg.SectionType,
	)
	var i Section
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Icon,
		&i.Cols,
		&i.Collapsed,
		&i.SortOrder,
		&i.SectionType,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
