// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: services.sql

package models

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createService = `-- name: CreateService :one
INSERT INTO services (title, url, description, icon, status_check, status_check_url, sort_order)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, title, url, description, icon, status_check, status_check_url, sort_order, created_at, updated_at
`

type CreateServiceParams struct {
	Title          string      `json:"title"`
	Url            string      `json:"url"`
	Description    string      `json:"description"`
	Icon           string      `json:"icon"`
	StatusCheck    bool        `json:"status_check"`
	StatusCheckUrl pgtype.Text `json:"status_check_url"`
	SortOrder      int32       `json:"sort_order"`
}

func (q *Queries) CreateService(ctx context.Context, arg CreateServiceParams) (Service, error) {
	row := q.db.QueryRow(ctx, createService,
		arg.Title,
		arg.Url,
		arg.Description,
		arg.Icon,
		arg.StatusCheck,
		arg.StatusCheckUrl,
		arg.SortOrder,
	)
	var i Service
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Url,
		&i.Description,
		&i.Icon,
		&i.StatusCheck,
		&i.StatusCheckUrl,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteService = `-- name: DeleteService :exec
DELETE FROM services WHERE id = $1
`

func (q *Queries) DeleteService(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteService, id)
	return err
}

const getService = `-- name: GetService :one
SELECT id, title, url, description, icon, status_check, status_check_url, sort_order, created_at, updated_at FROM services WHERE id = $1
`

func (q *Queries) GetService(ctx context.Context, id pgtype.UUID) (Service, error) {
	row := q.db.QueryRow(ctx, getService, id)
	var i Service
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Url,
		&i.Description,
		&i.Icon,
		&i.StatusCheck,
		&i.StatusCheckUrl,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listServices = `-- name: ListServices :many
SELECT id, title, url, description, icon, status_check, status_check_url, sort_order, created_at, updated_at FROM services ORDER BY sort_order ASC
`

func (q *Queries) ListServices(ctx context.Context) ([]Service, error) {
	rows, err := q.db.Query(ctx, listServices)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Service{}
	for rows.Next() {
		var i Service
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Url,
			&i.Description,
			&i.Icon,
			&i.StatusCheck,
			&i.StatusCheckUrl,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listServicesBySection = `-- name: ListServicesBySection :many
SELECT s.id, s.title, s.url, s.description, s.icon, s.status_check, s.status_check_url, s.sort_order, s.created_at, s.updated_at
FROM services s
JOIN service_section_mappings m ON m.service_id = s.id
WHERE m.section_id = $1
ORDER BY m.sort_order ASC
`

func (q *Queries) ListServicesBySection(ctx context.Context, sectionID pgtype.UUID) ([]Service, error) {
	rows, err := q.db.Query(ctx, listServicesBySection, sectionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Service{}
	for rows.Next() {
		var i Service
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Url,
			&i.Description,
			&i.Icon,
			&i.StatusCheck,
			&i.StatusCheckUrl,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateService = `-- name: UpdateService :one
UPDATE services
SET title = $2, url = $3, description = $4, icon = $5, status_check = $6,
    status_check_url = $7, sort_order = $8, updated_at = now()
WHERE id = $1
RETURNING id, title, url, description, icon, status_check, status_check_url, sort_order, created_at, updated_at
`

type UpdateServiceParams struct {
	ID             pgtype.UUID `json:"id"`
	Title          string      `json:"title"`
	Url            string      `json:"url"`
	Description    string      `json:"description"`
	Icon           string      `json:"icon"`
	StatusCheck    bool        `json:"status_check"`
	StatusCheckUrl pgtype.Text `json:"status_check_url"`
	SortOrder      int32       `json:"sort_order"`
}

func (q *Queries) UpdateService(ctx context.Context, arg UpdateServiceParams) (Service, error) {
	row := q.db.QueryRow(ctx, updateService,
		arg.ID,
		arg.Title,
		arg.Url,
		arg.Description,
		arg.Icon,
		arg.StatusCheck,
		arg.StatusCheckUrl,
		arg.SortOrder,
	)
	var i Service
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Url,
		&i.Description,
		&i.Icon,
		&i.StatusCheck,
		&i.StatusCheckUrl,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
